# Generated by Django 4.2.1 on 2024-01-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_slug_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
